nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.0.2.cjs

injectEnvironmentFiles:
  - .env?
npmScopes:
  chika3742:
    npmRegistryServer: https://npm.pkg.github.com
    npmAuthToken: ${GH_PACKAGES_TOKEN}